# Generated by Django 4.0.5 on 2023-02-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='like2',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='url',
        ),
        migrations.AddField(
            model_name='quarto',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='likes',
            name='quarto',
        ),
        migrations.AddField(
            model_name='likes',
            name='quarto',
            field=models.ManyToManyField(to='quartos.quarto'),
        ),
    ]
