# Generated by Django 4.0.5 on 2023-02-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0002_remove_likes_like2_remove_quarto_url_quarto_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='file',
        ),
        migrations.AddField(
            model_name='quarto',
            name='imagem',
            field=models.URLField(null=True),
        ),
    ]
