# Generated by Django 4.0.8 on 2023-02-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=512)),
                ('like', models.BooleanField(default=False)),
            ],
        ),
    ]
