# Generated by Django 4.0.8 on 2023-02-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_quarto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='like',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='url',
        ),
        migrations.AddField(
            model_name='quarto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
